spring.application.name=Delivery Service
# Toon SQL queries
spring.jpa.show-sql=true
server.port=7070
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.sql.init.data-locations=classpath*:sql/data.sql

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=delivery
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.sql=debug
logging.level.web=debug

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

#variable
payout.standard.compensation=3.5
payout.standard.incremental=0.3

# Exchanges
rabbit.delivery.response.exchange=delivery-response-exchange
rabbit.restaurant.response.exchange=restaurant-response-exchange

# Queues
rabbit.delivery.accept.queue=delivery-accept-queue
rabbit.delivery.ready.queue=delivery-ready-queue

rabbit.delivery.order.claimed=order.claimed.
rabbit.delivery.order.pickedup=order.pickedup.
rabbit.delivery.order.deliverd=order.deliverd.


# Security Catalog OAuth2 config
security.catalog.base-url=http://localhost:8080/realms/myrealm/protocol/openid-connect/token
security.catalog.client-id=backend-client
security.catalog.client-secret=NHhC580gogEpJ5K9fqsiyLiqF4VpqTKE
security.catalog.username=courier
security.catalog.password=password
security.catalog.grant-type=password
security.catalog.scope=openid


#keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/keepdishesgoing
security-catalog-api.url=http://localhost:8180/realms/keepdishesgoing/protocol/openid-connect/token
